version: '3.4'
services:
  web:
     container_name: tms_service_container
     build: .
     ports:
       - "8080:8080"
     depends_on:
       - db
     environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskManagement
       - SPRING_DATASOURCE_USERNAME=postgres
       - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:14-alpine
    container_name: tms_db_container
    ports:
    - "6541:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "taskManagement"